# Generated by Django 6.0.2 on 2026-02-16 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_quizresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='video_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
