# Generated by Django 5.1.4 on 2026-02-16 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0003_course_video_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="quizresult",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
