# Generated by Django 6.0.2 on 2026-02-22 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_studentprofile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecontent',
            name='video_file',
            field=models.FileField(blank=True, help_text='Upload .mp4 video files here', null=True, upload_to='course_videos/'),
        ),
    ]
