# Generated by Django 6.0.2 on 2026-02-23 00:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_assignment_assignmentsubmission_exam_examquestion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreativeQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stimulus', models.TextField(help_text='উদ্দীপক বা অনুচ্ছেদ লিখুন')),
                ('question_k', models.CharField(help_text='ক - জ্ঞানমূলক (১ মার্ক)', max_length=500)),
                ('question_kh', models.CharField(help_text='খ - অনুধাবনমূলক (২ মার্ক)', max_length=500)),
                ('question_g', models.CharField(help_text='গ - প্রয়োগমূলক (৩ মার্ক)', max_length=500)),
                ('question_gh', models.CharField(help_text='ঘ - উচ্চতর দক্ষতামূলক (৪ মার্ক)', max_length=500)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cq_questions', to='students.exam')),
            ],
        ),
        migrations.CreateModel(
            name='ExamWrittenSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_file', models.FileField(help_text='স্টুডেন্ট তার খাতায় লেখা উত্তরের ছবি বা PDF আপলোড করবে', upload_to='exams/cq_answers/')),
                ('marks_obtained', models.IntegerField(blank=True, default=0, null=True)),
                ('is_graded', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='written_submissions', to='students.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
