# Generated by Django 5.1.3 on 2026-02-23 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0004_alter_course_id_alter_quizresult_id"),
        ("students", "0009_creativequestion_examwrittensubmission"),
    ]

    operations = []
