# Generated by Django 6.0.2 on 2026-09-16 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_manualquizsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='enrolled_students', to='students.course'),
        ),
    ]
