# Generated by Django 6.0.2 on 2026-09-16 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_studentprofile_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='courses',
        ),
    ]
